baseURL: https://zeszyt.lapacz-kornel.dev/
languageCode: pl
title: Zeszyt Kornela
disableKinds: ['RSS']
params:
  author: Korneliusz Łapacz
  description: Na tej stronie znajdują się moje notatki z lekcji
  repo: https://github.com/kornellapacz/zeszyt
  feed: https://github.com/kornellapacz/zeszyt/commits/master.atom
markup: 
  highlight: 
    style: dracula