baseURL: https://zeszyt.klapacz.dev/
languageCode: pl
title: Zeszyt Kornela
disableKinds: ['RSS', 'section']
params:
  author: Korneliusz Łapacz
  description: Na tej stronie znajdują się moje notatki z lekcji
  repo: https://github.com/klapacz/zeszyt
  feed: https://github.com/klapacz/zeszyt/commits/master.atom
markup: 
  highlight: 
    style: dracula
taxonomies: {}

